name: shopify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  achievement_view: ^1.0.1
  animate_do: ^3.3.2
  badges: ^3.1.2
  bloc_concurrency: ^0.2.4
  cached_network_image: 3.4.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.2.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_core: ^3.3.0
  firebase_dynamic_links: ^6.0.4
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_zoom_drawer: ^3.1.2
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  liquid_pull_to_refresh: ^3.0.1
  loading_indicator: ^3.1.1
  package_info_plus: ^8.0.2
  permission_handler: ^11.2.0
  pretty_dio_logger: ^1.3.1
  restart_app: ^1.2.1
  retrofit: ^4.0.3
  share_plus: ^10.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  very_good_analysis: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/core/play_store_512.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/icons/
    - assets/svg/
    - assets/fonts/
    - lang/
    - .env.dev
    - .env.prod

  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
