// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkSdjZs-x12VpncPdZYCNta4WlzXjCXN8',
    appId: '1:1038310029523:web:11cddb0275546e1fbf7c26',
    messagingSenderId: '1038310029523',
    projectId: 'shopify-79776',
    authDomain: 'shopify-79776.firebaseapp.com',
    storageBucket: 'shopify-79776.appspot.com',
    measurementId: 'G-9P68JHT5S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOHZsknTRGjh_akW07QOnSuwruD4VoKTY',
    appId: '1:1038310029523:android:f908607787a91ca5bf7c26',
    messagingSenderId: '1038310029523',
    projectId: 'shopify-79776',
    storageBucket: 'shopify-79776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdBJz5JjLRAPZBRS_Oo5-pnweBsiXvaIM',
    appId: '1:1038310029523:ios:f29f15d8792185f4bf7c26',
    messagingSenderId: '1038310029523',
    projectId: 'shopify-79776',
    storageBucket: 'shopify-79776.appspot.com',
    iosBundleId: 'com.example.newfolder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdBJz5JjLRAPZBRS_Oo5-pnweBsiXvaIM',
    appId: '1:1038310029523:ios:f29f15d8792185f4bf7c26',
    messagingSenderId: '1038310029523',
    projectId: 'shopify-79776',
    storageBucket: 'shopify-79776.appspot.com',
    iosBundleId: 'com.example.newfolder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkSdjZs-x12VpncPdZYCNta4WlzXjCXN8',
    appId: '1:1038310029523:web:1ea56e51657a8318bf7c26',
    messagingSenderId: '1038310029523',
    projectId: 'shopify-79776',
    authDomain: 'shopify-79776.firebaseapp.com',
    storageBucket: 'shopify-79776.appspot.com',
    measurementId: 'G-EDMC66GJ4Q',
  );
}
