// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFlllIV1xhf6Fj5iwtUqBG-drL9Po4IP4',
    appId: '1:477227317931:web:724d40864b84be132955ee',
    messagingSenderId: '477227317931',
    projectId: 'shopify-761e9',
    authDomain: 'shopify-761e9.firebaseapp.com',
    storageBucket: 'shopify-761e9.appspot.com',
    measurementId: 'G-YG737X9D34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-kHbRffcU1yIys3S1PFYrzF2yIraxCg',
    appId: '1:477227317931:android:71307fdc66bef1552955ee',
    messagingSenderId: '477227317931',
    projectId: 'shopify-761e9',
    storageBucket: 'shopify-761e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDliGy2OzGIaAqnkuppQZk-f7a_tTcsJ2A',
    appId: '1:477227317931:ios:9101084f64bd65cf2955ee',
    messagingSenderId: '477227317931',
    projectId: 'shopify-761e9',
    storageBucket: 'shopify-761e9.appspot.com',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDliGy2OzGIaAqnkuppQZk-f7a_tTcsJ2A',
    appId: '1:477227317931:ios:9101084f64bd65cf2955ee',
    messagingSenderId: '477227317931',
    projectId: 'shopify-761e9',
    storageBucket: 'shopify-761e9.appspot.com',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFlllIV1xhf6Fj5iwtUqBG-drL9Po4IP4',
    appId: '1:477227317931:web:cfbbe18e9fd6b44b2955ee',
    messagingSenderId: '477227317931',
    projectId: 'shopify-761e9',
    authDomain: 'shopify-761e9.firebaseapp.com',
    storageBucket: 'shopify-761e9.appspot.com',
    measurementId: 'G-B08NQTDR85',
  );
}
